import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import '../assets/scss/layout/_layout.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div id="container">
          <header id="header-content">
            <Navbar />
          </header>
          <main id="main-content">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  )
}
